// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDW-UFhzDuZGC7PbePnTXgbV_kAFUg4XnE',
    appId: '1:596572487077:web:9cd9546e7a514d11e8fc4c',
    messagingSenderId: '596572487077',
    projectId: 'kakurodb-41e90',
    authDomain: 'kakurodb-41e90.firebaseapp.com',
    storageBucket: 'kakurodb-41e90.appspot.com',
    measurementId: 'G-FBPEWRZHL7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTewxg-BQtSvvd_CHVlK7bQvqPRhD3jwk',
    appId: '1:596572487077:android:6aa3d512544430dbe8fc4c',
    messagingSenderId: '596572487077',
    projectId: 'kakurodb-41e90',
    storageBucket: 'kakurodb-41e90.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqXgiZCtneZnIhS3NEo24NCmMCppjG8RU',
    appId: '1:596572487077:ios:c748c9f5a7f1a3b9e8fc4c',
    messagingSenderId: '596572487077',
    projectId: 'kakurodb-41e90',
    storageBucket: 'kakurodb-41e90.appspot.com',
    iosClientId: '596572487077-i92uplhfb62meqj6t2ha19k09qd0s7ll.apps.googleusercontent.com',
    iosBundleId: 'com.example.kakuro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqXgiZCtneZnIhS3NEo24NCmMCppjG8RU',
    appId: '1:596572487077:ios:c748c9f5a7f1a3b9e8fc4c',
    messagingSenderId: '596572487077',
    projectId: 'kakurodb-41e90',
    storageBucket: 'kakurodb-41e90.appspot.com',
    iosClientId: '596572487077-i92uplhfb62meqj6t2ha19k09qd0s7ll.apps.googleusercontent.com',
    iosBundleId: 'com.example.kakuro',
  );
}
